export const SITE_TITLE = 'Weekend Coder&apos; Chronicles'
export const SITE_DESCRIPTION = 'Blog created using Notion as a CMS'
export const SITE_KEYWORDS = 'blog, notion, cms, notion-blog'
export const SITE_AUTHOR = 'Utkarsh Nagar'
export const SITE_URL = ''